services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/root/.ollama/models
      - ./ollama/entrypoint.sh:/root/entrypoint.sh
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    entrypoint: /root/entrypoint.sh
    restart: unless-stopped
    networks:
      - dialogue-systems-course-network

networks:
  dialogue-systems-course-network:
    driver: bridge
